#!/bin/bash

# Prepare configuration directory and permission
if [ ! -d /var/www/etc ]; then
  mkdir -p /var/www/etc
fi
if [ ! -d /var/www/etc/httpd ]; then
  mkdir -p /var/www/etc/httpd
fi
if [ ! -d /var/www/etc/httpd/conf ]; then
  mkdir -p /var/www/etc/httpd/conf
fi
if [ ! -d /var/www/etc/php ]; then
  mkdir -p /var/www/etc/php
fi
if [ ! -d /var/www/etc/php/php-fpm.d ]; then
  mkdir -p /var/www/etc/php/php-fpm.d
fi
if [ ! -d /var/www/etc/composer ]; then
  mkdir -p /var/www/etc/composer
fi
if [ ! -d /var/www/html ]; then
  mkdir -p /var/www/html
fi


# Prepare HttpD configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/etc/httpd/conf/httpd.conf ]; then
  cp /etc/httpd/conf/httpd.conf.docker /var/www/etc/httpd/conf/httpd.conf
fi


# Prepare PHP HttpD configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/etc/php/php.ini ]; then
  cp /etc/php.ini.docker /var/www/etc/php/php.ini
fi
if [ ! -f /var/www/etc/php/php-fpm.d/www.conf ]; then
  cp /etc/php-fpm.d/www.conf.docker /var/www/etc/php/php-fpm.d/www.conf
fi


# Prepare Default Web Content file if the file doesn't exist
# due to volume support
if [[ ! -f /var/www/html/index.php && ! -f /var/www/html/public/index.php ]]; then
  cp /usr/share/docker/files/www/index.php /var/www/html/index.php
  cp /usr/share/docker/files/www/info.php /var/www/html/info.php
fi

# Try to start PHP-FPM on daemonize mode
/usr/sbin/php-fpm --daemonize


# Try to start HttpD on non-daemonize mode
/usr/sbin/httpd -D FOREGROUND


# End the script
exit 0
