#!/bin/bash

# Prepare configuration directory and permission
if [ ! -d /var/www/html ]; then
  mkdir -p /var/www/html
fi
if [ ! -d /var/www/cgi-bin ]; then
  mkdir -p /var/www/cgi-bin
fi
if [ ! -d /var/www/etc ]; then
  mkdir -p /var/www/etc
fi
if [ ! -d /var/www/etc/apache2 ]; then
  mkdir -p /var/www/etc/apache2
fi
if [ ! -d /var/www/etc/php ]; then
  mkdir -p /var/www/etc/php
fi
if [ ! -d /var/www/etc/php/5.6 ]; then
  mkdir -p /var/www/etc/php/5.6
fi
if [ ! -d /var/www/etc/php/5.6/fpm ]; then
  mkdir -p /var/www/etc/php/5.6/fpm
fi
if [ ! -d /var/www/etc/php/5.6/fpm/pool.d ]; then
  mkdir -p /var/www/etc/php/5.6/fpm/pool.d
fi
if [ ! -d /var/www/etc/composer ]; then
  mkdir -p /var/www/etc/composer
fi
if [ ! -d /var/lib/php/sessions ]; then
  mkdir -p /var/lib/php/sessions
fi
if [ ! -d /var/lib/php/uploads ]; then
  mkdir -p /var/lib/php/uploads
fi
if [ $UID == 0 ]; then
  chown user:root /var/lib/php/sessions
  chown user:root /var/lib/php/uploads
fi



# Prepare Apache configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/etc/apache2/apache2.conf ]; then
  cp /etc/apache2/apache2.conf.docker /var/www/etc/apache2/apache2.conf
fi


# Prepare PHP Apache configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/etc/php/5.6/fpm/php.ini ]; then
  cp /etc/php/5.6/fpm/php.ini.docker /var/www/etc/php5.6/fpm/php.ini
fi
if [ ! -f /var/www/etc/php/5.6/fpm/pool.d/www.conf ]; then
  cp /etc/php/5.6/fpm/pool.d/www.conf.docker /var/www/etc/php/5.6/fpm/pool.d/www.conf
fi


# Prepare Default Web Content file if the file doesn't exist
# due to volume support
if [[ ! -f /var/www/html/index.php && ! -f /var/www/html/public/index.php ]]; then
  cp /usr/share/docker/files/www/index.php /var/www/html/index.php
  cp /usr/share/docker/files/www/info.php /var/www/html/info.php
fi


# Try to start PHP-FPM on daemonize mode
/usr/sbin/php-fpm5.6 --daemonize


# Try to start Apache on non-daemonize mode
/usr/sbin/apache2ctl -D FOREGROUND


# End the script
exit 0
