#!/bin/bash

# Prepare configuration directory and permission
if [ ! -d /var/www/html ]; then
  mkdir -p /var/www/html
fi
if [ ! -d /var/www/etc ]; then
  mkdir -p /var/www/etc
fi
if [ ! -d /var/www/etc/nginx ]; then
  mkdir -p /var/www/etc/nginx
fi
if [ ! -d /var/www/etc/nginx/conf.d ]; then
  mkdir -p /var/www/etc/nginx/conf.d
fi
if [ ! -d /var/www/etc/php ]; then
  mkdir -p /var/www/etc/php
fi
if [ ! -d /var/www/etc/php/php-fpm.d ]; then
  mkdir -p /var/www/etc/php/php-fpm.d
fi
if [ ! -d /var/www/etc/php/lib ]; then
  mkdir -p /var/www/etc/php/lib
fi
if [ ! -d /var/www/etc/php/lib/sessions ]; then
  mkdir -p /var/www/etc/php/lib/sessions
fi
if [ ! -d /var/www/etc/php/lib/uploads ]; then
  mkdir -p /var/www/etc/php/lib/uploads
fi
if [ ! -d /var/www/etc/composer ]; then
  mkdir -p /var/www/etc/composer
fi
if [ $UID == 0 ]; then
  chown user:root /var/www/etc/php/lib/sessions
  chown user:root /var/www/etc/php/lib/uploads
fi


# Prepare Nginx configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/etc/nginx/conf.d/default.conf ]; then
  cp /etc/nginx/conf.d/default.conf.docker /var/www/etc/nginx/conf.d/default.conf
fi


# Prepare PHP-FPM configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/etc/php/php.ini ]; then
  cp /etc/php.ini.docker /var/www/etc/php/php.ini
fi
if [ ! -f /var/www/etc/php/php-fpm.d/www.conf ]; then
  cp /etc/php-fpm.d/www.conf.docker /var/www/etc/php/php-fpm.d/www.conf
fi


# Prepare Default Web Content file if the file doesn't exist
# due to volume support
if [[ ! -f /var/www/html/index.php && ! -f /var/www/html/public/index.php ]]; then
  cp /usr/share/docker/files/www/index.php /var/www/html/index.php
  cp /usr/share/docker/files/www/info.php /var/www/html/info.php
fi


# Try to start PHP-FPM on daemonize mode
/usr/sbin/php-fpm --daemonize


# Try to start Nginx on non-daemonize mode
/usr/sbin/nginx


# End the script
exit 0
