#!/bin/bash

if [ "$(id -u)" != "0" ]; then
  echo "user:x:`id -u`:0:User:/root:/sbin/nologin" >> /etc/passwd
else
  echo "user:x:901:0:User:/root:/sbin/nologin" >> /etc/passwd  
fi


jasperserver_setup() {
    JS_DB_TYPE=${JS_DB_TYPE:-mysql}
    JS_DB_HOST=${JS_DB_HOST:-127.0.0.1}
    JS_DB_PORT=${JS_DB_PORT:-3306}
    JS_DB_ROOT_USER=${JS_DB_ROOT_USER:-root}
    JS_DB_ROOT_PASSWORD=${JS_DB_ROOT_PASSWORD:-root}

    JS_WEB_DEPLOYMENT_URI=${JS_WEB_DEPLOYMENT_URI:-http://127.0.0.1:8080/}
    JS_ENABLE_SAVE_TO_HOST_FS=${JS_ENABLE_SAVE_TO_HOST_FS:-false}

    cd ${JS_BUILD} \
    && cp sample_conf/${JS_DB_TYPE}_master.properties default_master.properties \
    && sed -i -e "s|^appServerDir.*$|appServerDir = $CATALINA_HOME|g; s|^dbHost.*$|dbHost=$JS_DB_HOST|g; s|^dbUsername.*$|dbUsername=$JS_DB_ROOT_USER|g; s|^dbPassword.*$|dbPassword=$JS_DB_ROOT_PASSWORD|g" default_master.properties \
    && sed -i -e "s|^# quartz\.web\.deployment\.uri.*$|quartz.web.deployment.uri = $JS_WEB_DEPLOYMENT_URI|g" default_master.properties

    ./js-ant create-js-db init-js-db-ce import-minimal-ce || true
    for i in $@; do
        ./js-ant $i
    done

    if [ "${JS_ENABLE_SAVE_TO_HOST_FS}" = "true" ]; then
      sed -i "s/\(<property name=\"enableSaveToHostFS\" value=\"\).*\(\"\/>\)/\1${JS_ENABLE_SAVE_TO_HOST_FS}\2/" /usr/local/tomcat/webapps/jasperserver/WEB-INF/applicationContext.xml
    fi

    rm -rf $CATALINA_HOME/webapps/ROOT \
    && rm -rf $CATALINA_HOME/webapps/docs \
    && rm -rf $CATALINA_HOME/webapps/examples \
    && rm -rf $CATALINA_HOME/webapps/host-manager \
    && rm -rf $CATALINA_HOME/webapps/manager \
    && mv $CATALINA_HOME/webapps/jasperserver $CATALINA_HOME/webapps/ROOT \
    && sed -i "s/jasperserver\.root/ROOT.root/g" $CATALINA_HOME/webapps/ROOT/WEB-INF/web.xml \
    && sed -i "s/jasperserver\.root/ROOT.root/g" $CATALINA_HOME/webapps/ROOT/WEB-INF/log4j.properties \
    && echo "tbeller.usejndi=false" >> $CATALINA_HOME/webapps/ROOT/WEB-INF/classes/resfactory.properties \
    && touch $CATALINA_HOME/webapps/jasperserver
}


jasperserver_run() {
    if [ ! -f "$CATALINA_HOME/webapps/jasperserver" ]; then
        jasperserver_setup deploy-webapp-ce
    fi
    
    catalina.sh run
}


export CATALINA_OPTS="-Xmx${JS_XMX} -XX:MaxPermSize=${JS_MAXPERMSIZE} ${JS_CATALINA_OPTS}"
case "$1" in
    run)
        shift 1
        jasperserver_run "$@"
        ;;
    *)
        exec "$@"
esac
