#!/bin/bash

# Prepare configuration directory and permission
if [ ! -d /var/www/data/html ]; then
  mkdir -p /var/www/data/html
fi
if [ ! -d /var/www/data/etc ]; then
  mkdir -p /var/www/data/etc
fi
if [ ! -d /var/www/data/etc/nginx ]; then
  mkdir -p /var/www/data/etc/nginx
fi
if [ ! -d /var/www/data/etc/nginx/conf.d ]; then
  mkdir -p /var/www/data/etc/nginx/conf.d
fi
if [ ! -d /var/www/data/etc/php5 ]; then
  mkdir -p /var/www/data/etc/php5
fi
if [ ! -d /var/www/data/etc/php5/lib ]; then
  mkdir -p /var/www/data/etc/php5/lib
fi
if [ ! -d /var/www/data/etc/php5/lib/sessions ]; then
  mkdir -p /var/www/data/etc/php5/lib/sessions
fi
if [ ! -d /var/www/data/etc/php5/lib/uploads ]; then
  mkdir -p /var/www/data/etc/php5/lib/uploads
fi
if [ ! -d /var/www/data/etc/composer ]; then
  mkdir -p /var/www/data/etc/composer
fi
if [ $UID == 0 ]; then
  chown user:root /var/www/data/etc/php5/lib/sessions
  chown user:root /var/www/data/etc/php5/lib/uploads
fi


# Prepare Nginx configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/data/etc/nginx/conf.d/default.conf ]; then
  cp /etc/nginx/conf.d/default.conf.docker /var/www/data/etc/nginx/conf.d/default.conf
fi


# Prepare PHP-FPM configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/data/etc/php5/php.ini ]; then
  cp /etc/php5/php.ini.docker /var/www/data/etc/php5/php.ini
fi
if [ ! -f /var/www/data/etc/php5/php-fpm.conf ]; then
  cp /etc/php5/php-fpm.conf.docker /var/www/data/etc/php5/php-fpm.conf
fi


# Prepare Default Web Content file if the file doesn't exist
# due to volume support
if [[ ! -f /var/www/data/html/index.php && ! -f /var/www/data/html/public/index.php ]]; then
  cp /usr/share/docker/files/www/index.php /var/www/data/html/index.php
  cp /usr/share/docker/files/www/info.php /var/www/data/html/info.php
fi


# Try to start PHP-FPM on daemonize mode
/usr/bin/php-fpm --daemonize


# Try to start Nginx on non-daemonize mode
/usr/sbin/nginx


# End the script
exit 0
