#!/bin/bash

# Prepare Nginx configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/etc/nginx/sites-available/default ]; then
  mkdir -p /var/www/etc/nginx/sites-available
  cp /etc/nginx/sites-available/default.docker /var/www/etc/nginx/sites-available/default
fi


# Prepare PHP-FPM configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/etc/php5/fpm/php.ini ]; then
  mkdir -p /var/www/etc/php5/fpm
  cp /etc/php5/fpm/php.ini.docker /var/www/etc/php5/fpm/php.ini
fi
if [ ! -f /var/www/etc/php5/fpm/pool.d/www.conf ]; then
  mkdir -p /var/www/etc/php5/fpm/pool.d
  cp /etc/php5/fpm/pool.d/www.conf.docker /var/www/etc/php5/fpm/pool.d/www.conf
fi


# Prepare PHP Composer configuration directory if the directory doesn't exist
# due to volume support
if [ ! -d /var/www/etc/composer ]; then
  mkdir -p /var/www/etc/composer
fi


# Prepare Default Web Content file if the file doesn't exist
# due to volume support
if [[ ! -f /var/www/html/index.php && ! -f /var/www/html/public/index.php ]]; then
  cp /usr/share/docker/files/www/index.php /var/www/html/index.php
  cp /usr/share/docker/files/www/info.php /var/www/html/info.php
fi


# Try to start PHP-FPM on daemonize mode
/usr/sbin/php5-fpm --daemonize


# Try to start Nginx on non-daemonize mode
/usr/sbin/nginx


# End the script
exit 0
