#!/bin/bash

set -e

if [ "$(id -u)" != "0" ]; then
  echo "user:x:`id -u`:0:User:/root:/sbin/nologin" >> /etc/passwd
else
  echo "user:x:901:0:User:/root:/sbin/nologin" >> /etc/passwd  
fi

ulimit -c 0

catalina_run() {
  if [ "$(ls -A $CATALINA_HOME/webapps)" ]; then
    :
  else
    cp -R $CATALINA_HOME/webapps-docker/* $CATALINA_HOME/webapps/
  fi
  
  catalina.sh run
}

case "$1" in
  run)
    shift 1
    catalina_run "$@"
    ;;
  *)
    exec "$@"
esac
