version: '2'

networks:
  kafkanet:
    driver: bridge

services:
  zookeeper:
    image: 'dimaskiddo/alpine:kafka-2.1'
    networks:
      - kafkanet
    ports:
      - 2181:2181
    command:
      - zookeeper-server-start.sh
      - /opt/kafka/config/zookeeper.properties    
    restart: always

  kafka:
    image: 'dimaskiddo/alpine:kafka-2.1'
    networks:
      - kafkanet
    ports:
      - 9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=topic:1:1
    depends_on:
      - zookeeper
    restart: always
