# Docker Compose API Version
version: '2'

networks:
  # Create "PyBridge" Bridge Network
  pybridge:
    driver: bridge

services:
  # Application 1: Redis (Database Application)
  redis:
    image: dimaskiddo/alpine:redis-3.2
    networks:
      - pybridge
    volumes:
      - ./data/redis:/data/redis:rw
    restart: always

  # Application 2: App (Main Application)
  app:
    build: ./app
    image: dimaskiddo/sample:python-2.7
    networks:
      - pybridge
    environment:
      - NAME=World
    depends_on:
      - redis
    restart: always

  # Application 3: Nginx (Load Balancer)
  nginx:
    image: dimaskiddo/alpine:nginx-1.12.2-novol
    networks:
      - pybridge
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./conf/nginx:/var/www/data/etc/nginx:rw
    depends_on:
      - app
    restart: always
