#!/bin/bash

# Add Custom UserID as "User" User
if [ "$(id -u)" != "0" ]; then
  echo "user:x:`id -u`:0:User:/root:/sbin/nologin" >> /etc/passwd
else
  echo "user:x:901:0:User:/root:/sbin/nologin" >> /etc/passwd  
fi


# Limit User from Root
ulimit -c 0


# Execute Everything from Entries
exec "$@"
