#!/bin/bash

# Prepare configuration directory and permission
if [ ! -d /var/www/etc ]; then
  mkdir -p /var/www/etc
fi
if [ ! -d /var/www/etc/apache2 ]; then
  mkdir -p /var/www/etc/apache2
fi
if [ ! -d /var/www/etc/php5 ]; then
  mkdir -p /var/www/etc/php5
fi
if [ ! -d /var/www/etc/php5/apache2 ]; then
  mkdir -p /var/www/etc/php5/apache2
fi
if [ ! -d /var/www/etc/composer ]; then
  mkdir -p /var/www/etc/composer
fi
if [ ! -d /var/www/html ]; then
  mkdir -p /var/www/html
fi


# Prepare Apache configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/etc/apache2/apache2.conf ]; then
  cp /etc/apache2/apache2.conf.docker /var/www/etc/apache2/apache2.conf
fi


# Prepare PHP Apache configuration file if the file doesn't exist
# due to volume support
if [ ! -f /var/www/etc/php5/apache2/php.ini ]; then
  cp /etc/php5/apache2/php.ini.docker /var/www/etc/php5/apache2/php.ini
fi


# Prepare Default Web Content file if the file doesn't exist
# due to volume support
if [[ ! -f /var/www/html/index.php && ! -f /var/www/html/public/index.php ]]; then
  cp /usr/share/docker/files/www/index.php /var/www/html/index.php
  cp /usr/share/docker/files/www/info.php /var/www/html/info.php
fi

# Try to start Apache on non-daemonize mode
/usr/sbin/apache2ctl -D FOREGROUND


# End the script
exit 0
